apiVersion: v1
kind: Service
metadata:
  name: infra-guardian
spec:
  type: {{ .Values.service.type }}
  selector:
    app: infra-guardian
  ports:
    - name: http
      port: 3000
      targetPort: 3000
