apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-guardian-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-guardian-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "events", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-guardian-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-guardian-reader
subjects:
  - kind: ServiceAccount
    name: infra-guardian-sa
    namespace: default

